# Generated by Django 4.2 on 2023-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_produitnc_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
